name: Build and publish docker images
on:
  workflow_call:
    inputs:
      platforms:
        description: > 
          Specify which platforms to build an image for. Forwarded to 
          docker/build-push-action@v2.
        type: string
        required: false
        default: linux/amd64,linux/arm64
      image-name:
        description: >
          What to call the docker image. Does not include a tag name. You need to 
          include the 'matrixdotorg/' prefix.
        type: string
        required: true
      dockerfile:
        description: Path to the Dockerfile, relative to the repository root.
        type: string
        required: false
        default: Dockerfile
      publish:
        description: If true, publish to dockerhub.
        type: boolean
        required: false
        default: false
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: inputs.platforms != 'linux/amd64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: docker buildx inspect
          
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # TODO: consider using https://github.com/docker/metadata-action instead of this
      # custom magic
      - name: Calculate docker image tag
        id: set-tag
        run: |
          case "${GITHUB_REF}" in
              refs/heads/develop)
                  tag=develop
                  ;;
              refs/heads/master|refs/heads/main)
                  tag=latest
                  ;;
              refs/tags/*)
                  tag=${GITHUB_REF#refs/tags/}
                  ;;
              *)
                  tag=${GITHUB_SHA}
                  ;;
          esac
          echo "::set-output name=tag::$tag"

      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.publish }}
          labels: "gitsha1=${{ github.sha }}"
          tags: "${{ inputs.image-name }}:${{ steps.set-tag.outputs.tag }}"
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
